# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - "*"


pool: AWS-D60

resources:
  repositories:
  - repository: shared-library
    name: jenkins
    type: git

variables:
  COMPONENT: cart

stages:

  - stage: CompileCode
      jobs:
          - job: CompileCode
            steps:
              - script: echo Compile Code - ${COMPONENT}
                name: CompileCode
  - stage: TestCases
    condition: in(dependencies.CompileCode.result, 'Succeeded')
    #condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    jobs:
      - job: TestCases
        steps:
          - script: echo Test Cases
            name: TestCases
      - job: TestCases1
        dependsOn:
          - TestCases
        steps:
          - script: echo Test Cases
            name: TestCases
-  # template: test.yml@shared-library
